language: node_js
node_js: node
script:
- npm run coverage
after_script:
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
before_install:
- export TZ=Asia/Shanghai
- date
deploy:
  provider: npm
  email: iskyzh@gmail.com
  api_key:
    secure: KF5l8gpU8VO0biV7JShl/mKgDonpQFMuIuJpjkRhOIzLNREScW9lXacMxaqUU8YVEvsqBGqNZfkCE9nc+0qzr7QVRkfoq+t2M1QmOk0ouNJrdN3UWXJjyHsduxr/IwsAUSXJEZMIRspDMh/+E2Hj86ndT1GDz9wJ5A6+//FPcMgXRcAroEiFvMVKkDwWHa+d/g8IxeoSbQZdDetZRE1tSpnO5JM2DILmMhT71b6sRDHUZTrpNJG72gV9c/bCAqFJLcSiNR59a7MS6fhlcDgQo2g2oqez61Rks3fS+DLZ4AJhqr4Zt44Xqw0qx0HNiDWcS/pm/IVmzVd3MEHDRvffga5SZR9nY7H5ZOpAwLwdK6SZsEx/6MpbvNZ7ecS3qNsKMlxsPzhNWmy1df9Gc4cGBhfKuO1hRmUWWjf8TVWQRkYADEfv9xZdG2go4FTd3rufu7qbIh2wBb604Lc0AGKiwWMCtRjFzXBgcUb0CclUIDtXihPNs8wJ28Hki3g0LiXRaI6nh0ZFtWSB3+Q7Fdpybf+GRUM84uKPM/IpPEKKJ0HyqdC1ToW65W5c4h2DCZVcs1/lLzIhjFGDwLRXbuZNbozphKG32xpAqJP3bUKmuVLhpCYtRsLfn7PlfM24R5G05iNHwZdGTAZNFNY+u5A3OFViK3vykAblL+ZdSO5SBug=
  on:
    repo: SkyZH/ticktick
  skip_cleanup: true
cache:
  yarn: true
  directories:
  - node_modules
