language: node_js
node_js: node
script:
- npm run coverage
after_script:
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
before_install:
- export TZ=Asia/Shanghai
- date
deploy:
  provider: npm
  email: iskyzh@gmail.com
  api_key:
    secure: c+HipJCJKhjQG6ty1dGSINGwmKA9MR01d6s0fZXpCs5nVfLfH68XNHVKZQu8GPp4zmzgAZwIr5tyx61xUs8tL1Z02+gHRT9IO92zngdCcAunC6+z53TOP6/mzYMtdHDX4nO9axIgdUqJ4DN3H59NQAPMsztFCEbOokGcpr4a0Iu5URYXqxPObhRwYug15ylBoMCOfrmgiv0SpIeS+E3hww2g7VGRrt3WBXvl/JTnxS1wZmxMfxOgTvYaO/zi7VyKEIhVifY6TA2/1ALf41Xo6MsCvDw+9wXv1QVxXCglEL5o48wUdLoXE6zj9kLCzWm/khV8hEMJ9CaA/DT9yZRJELC9KTi97114AqcoHiU+YEG6poV1OEiUFi/KHtcutTA218uZ1D9X8BxNbFtoB5uIZ+ZtRh9vdIaO1HKa470xvSmrKNzPeQxwQSqtSOHrqscCNiB/8Hu8DeWTIIKfMzZEBcpzcfDjQ+MohMk/BIxo65E6rCnJUJ2xzQDJXE9AGSNYa4Vsgk8hK2RcFTd0sdSY1uJ4A73960s0hxvgPl1YHMPy/QcGC46GG5LfNVDzB9smZzJUB+B5+LkAmzy5pL800ATl23QGNXgnld20v1yQ/Lg+F6jNLgbP3UN41hLY2d/50189z7HtlEGvjO/gADX8x8YiV5MnDZZXsZKy8FMZTeE=
  on:
    repo: SkyZH/ticktick
cache:
  yarn: true
  directories:
    - node_modules
